-- Migration 012: Add source column to businesses for tracking data origin
-- Values: 'manual' (hand-created), 'seed' (generated by seed script), 'scraped' (from scraping pipeline)

ALTER TABLE businesses ADD COLUMN IF NOT EXISTS source VARCHAR(50) DEFAULT 'manual';

-- Tag existing seed data
UPDATE businesses SET source = 'seed' WHERE logo_url LIKE '%dicebear%' OR cover_image_url LIKE '%picsum%';
