-- Migration 073: Performance indexes
-- Original indexes were redundant with existing ones from migrations 023, 028, 047.
-- idx_followed_biz_bid_created: redundant with idx_followed_businesses_business_id (023)
-- idx_offer_views_composite: redundant with idx_offer_views_bid_date (047)
-- Kept as no-op to maintain migration numbering.
